name: Build Windows AMD64

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"

    - name: Cache Dependencies & Nuitka
      uses: actions/cache@v4
      with:
        path: |
          .venv
          ~\AppData\Local\Nuitka\Nuitka
        key: ${{ runner.os }}-build-${{ github.run_id }}
        restore-keys: |
          ${{ runner.os }}-build-

    - name: Build with Nuitka
      run: |
        .\Scripts\build.bat
      shell: cmd

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: DrissionPage-win-amd64
        path: dist/*
